# Generated by Django 5.2.13 on 2026-06-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
